export const propertiesData = [
  {
    cod: 1,
    name: 'Casa en Condominio',
    address: {
      street: 'Av. Apoquindo 5000',
      city: 'Las Condes',
      country: 'Chile',
    },
    price: 1000000,
    image: '',
    squareMeters: 100,
  },
  {
    cod: 2,
    name: 'Agricola en Donilhue',
    address: {
      street: 'Rinconada de Donilhue',
      city: 'La Quisca',
      country: 'Chile',
    },
    price: 1000000,
    image: '',
    squareMeters: 100,
  },
  {
    cod: 3,
    name: 'Agricola en Donilhue',
    address: {
      street: 'Rinconada de Donilhue',
      city: 'La Quisca',
      country: 'Chile',
    },
    price: 1000000,
    image: '',
    squareMeters: 100,
  },
  {
    cod: 4,
    name: 'Agricola en Donilhue',
    address: {
      street: 'Rinconada de Donilhue',
      city: 'La Quisca',
      country: 'Chile',
    },
    price: 1000000,
    image: '',
    squareMeters: 100,
  },
  {
    cod: 5,
    name: 'Agricola en Donilhue',
    address: {
      street: 'Rinconada de Donilhue',
      city: 'La Quisca',
      country: 'Chile',
    },
    price: 1000000,
    image: '',
    squareMeters: 100,
  },
  {
    cod: 6,
    name: 'Agricola en Donilhue',
    address: {
      street: 'Rinconada de Donilhue',
      city: 'La Quisca',
      country: 'Chile',
    },
    price: 1000000,
    image: '',
    squareMeters: 100,
  },
  {
    cod: 7,
    name: 'Agricola en Donilhue',
    address: {
      street: 'Rinconada de Donilhue',
      city: 'La Quisca',
      country: 'Chile',
    },
    price: 1000000,
    image: '',
    squareMeters: 100,
  },
  {
    cod: 8,
    name: 'Agricola en Donilhue',
    address: {
      street: 'Rinconada de Donilhue',
      city: 'La Quisca',
      country: 'Chile',
    },
    price: 1000000,
    image: '',
    squareMeters: 100,
  },
  {
    cod: 9,
    name: 'Agricola en Donilhue',
    address: {
      street: 'Rinconada de Donilhue',
      city: 'La Quisca',
      country: 'Chile',
    },
    price: 1000000,
    image: '',
    squareMeters: 100,
  },
];
